---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.0
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqlvolume
		  env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: openmrs
        - name: MYSQL_USER
          value: sharath
        - name: MYSQL_PASSWORD
          value: samineni
      volumes:
        - name: mysqlvolume
          persistentVolumeClaim:
            claimName: azure-managed-disk

---
apiVersion: v1
kind: Service
metadata:
  name: openmrssvc
spec:
  selector:
    app: openmrs
    version: "1.0"
  type: LoadBalancer
  ports:
    - port: 8080