---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: db
    ver: 8.0
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: openmrs
        - name: MYSQL_USER
          value: sharath
        - name: MYSQL_PASSWORD
          value: samineni       
