---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openmrs-rc
  labels:
    app: openmrs
spec:
  replicas: 3
  selector:
    app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      containers:
        - name: openmrs
          image: saminenikittu/openmrs:1.0
          ports:
            - containerPort: 49153
              protocol: TCP