---
apiVersion: v1
kind: Pod
metadata: 
  name: openmrs1
  labels:
    app: openmrs1
    ver: 1.0
spec:
  containers:
    - name: openmr1
      image: saminenikittu/dockerprac:openmrs
      ports:
        - containerPort: 49153
          protocol: TCP