---
apiVersion: v1
kind: Pod
metadata: 
  name: openmrs
  labels:
    app: openmrs
spec:
  containers:
    - name: openmrs
      image: saminenikittu/openmrs:1.0
      ports:
        - containerPort: 49153
          protocol: TCP